version: '3.8'
name: fsh-microservices

services:
  identity:
    container_name: identity
    image: fsh-microservices.identity:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
    volumes:
      - ${USERPROFILE}\.aspnet\https:/https
    depends_on:
      identity-pg:
        condition: service_healthy 
    networks:
     - fsh-microservices
  identity-pg:
    container_name: "identity-pg"
    image: postgres:15-alpine
    environment:
      - POSTGRES_DATABASE=admin
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGPORT=5210
    ports:
      - 5210:5210
    volumes:
      - identity-pg-data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
     - fsh-microservices
volumes:
  identity-pg-data:
    
