version: '3.8'
name: fluentpos

services:
  traefik:
    container_name: traefik
    image: traefik:latest
    command:
      - --log.level=DEBUG
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
     - fluentpos
  identity:
    container_name: identity
    image: iammukeshm/fluentpos.identity:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.identity.rule=(Host(`app.localhost`) && PathPrefix(`/identity`))
      - traefik.http.routers.identity.entrypoints=web
      - traefik.http.services.identity.loadbalancer.server.port=80
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
    depends_on:
      postgres:
        condition: service_healthy
    networks:
     - fluentpos
  catalog:
    container_name: catalog
    image: iammukeshm/fluentpos.catalog:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.catalog.rule=(Host(`app.localhost`) && PathPrefix(`/catalog`))
      - traefik.http.routers.catalog.entrypoints=web
      - traefik.http.services.catalog.loadbalancer.server.port=80
    depends_on:
      - mongo
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
    networks:
     - fluentpos
  cart:
    container_name: cart
    image: iammukeshm/fluentpos.cart:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.cart.rule=(Host(`app.localhost`) && PathPrefix(`/cart`))
      - traefik.http.routers.cart.entrypoints=web
      - traefik.http.services.cart.loadbalancer.server.port=80
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
    networks:
     - fluentpos