apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: redis
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    secretKeyRef:
      name: redis.host
      key: redis.host
  - name: redisPassword
    value: ""
auth:
  secretStore: secretstore
scopes:
- cart
- catalog
- identity
- gateway