apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: fluentpos-pubsub
  namespace: fluentpos
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: connectionString
    value: amqp://localhost:5672
  - name: durable
    value: false
  - name: deletedWhenUnused
    value: false
  - name: autoAck
    value: false
  - name: reconnectWait
    value: 0
  - name: concurrency
    value: parallel