version: '3.8'
name: fsh-microservices

services:
  catalog:
    container_name: catalog-service
    image: fsh-microservices.catalog:latest
    depends_on:
      - catalog-mongo
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
    volumes:
      - ${USERPROFILE}\.aspnet\https:/https
    networks:
     - fsh-microservices
  catalog-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "catalog",
     "-placement-host-address", "placement:50003"]
    depends_on:
      - catalog
    networks:
     - fsh-microservices
  catalog-mongo:
    image: mongo
    container_name: catalog-mongo
    restart: on-failure
    ports:
      - 27017:27017
    volumes:
      - catalog-mongo-data:/data/db
    networks:
      - fsh-microservices
volumes:
  catalog-mongo-data:
