version: '3.8'
name: fsh-microservices

services:
  gateway:
    container_name: "gateway"
    image: fsh-microservices.gateway:latest
    ports:
      - 5010:5010
      - 5100:5100
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
      - ASPNETCORE_URLS=https://+:5100;http://+:5010
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/dev_cert.pfx
    volumes:
      - ${USERPROFILE}\.aspnet\https:/https
    networks:
     - fsh-microservices
    
