version: '3.8'
name: fsh-microservices

services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGPORT=5430
    ports:
      - 5430:5430
    volumes:
      - postgres-data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
     - fsh-microservices

  mongo:
    image: mongo
    container_name: mongo
    restart: on-failure
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - fsh-microservices

  placement:
    container_name: dapr-placement
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - 50006:50006
    networks:
      - fsh-microservices

  redis:
    container_name: dapr-redis
    image: "redis:alpine"
    ports:
      - 6379:6379
    networks:
      - fsh-microservices

  elasticsearch:
   container_name: elasticsearch
   image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
   restart: unless-stopped
   ports:
    - 9200:9200
   volumes:
    - elasticsearch-data:/usr/share/elasticsearch/data
   environment:
    - xpack.monitoring.enabled=true
    - xpack.watcher.enabled=false
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - discovery.type=single-node
   networks:
    - fsh-microservices

  kibana:
   container_name: kibana
   image: docker.elastic.co/kibana/kibana:7.9.2
   restart: unless-stopped
   ports:
    - 5601:5601
   depends_on:
    - elasticsearch
   environment:
    - ELASTICSEARCH_URL=http://localhost:9200
   networks:
    - fsh-microservices

volumes:
  postgres-data:
  mongo-data:
  elasticsearch-data:

networks:
  fsh-microservices:
    name:  fsh-microservices
