name: release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
  test:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Test
      run: dotnet test --no-build --verbosity normal
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
      - name: Install Node dependencies
        run: npm ci    
      - name: Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
  docker:
    runs-on: ubuntu-latest
    needs:
      - release
    steps:
    - name: Checkout
      uses: actions/checkout@v3  
    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Catalog Service Image
      working-directory: ./
      run: dotnet publish src/services/catalog/Host/Host.csproj --os linux --arch x64 -c Release -p:PublishProfile=DefaultContainer -p:ContainerImageName=${{ github.actor }}/fsh-microservices.catalog
    - name: Push Catalog Service Image
      run: docker push ${{ github.actor }}/fsh-microservices.catalog --all-tags    
  cleanup:
    needs:
      - docker
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: "♻️ Removes Build Artifacts"
        uses: geekyeggo/delete-artifact@v1
        with:
          name: |
            build
            test
            release
            docker    