name: semantic-release

on:
  workflow_dispatch:

jobs:
  semantic-release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
      - name: Install Node dependencies
        run: npm ci    
      - name: Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Catalog Service Image
        working-directory: ./
        run: dotnet publish src/services/catalog/Host/Host.csproj --os linux --arch x64 -c Release -p:PublishProfile=DefaultContainer -p:ContainerImageName=${{ github.actor }}/fsh-microservices.catalog
      - name: Push Catalog Service Image
        run: docker push ${{ github.actor }}/fsh-microservices.catalog --all-tags    